### ISSUE TITLE
Java Bazel build not working due to path names

### ISSUE THREAD

**Issue by sweis** [google/tink#456]
The [Java Hacking](https://github.com/google/tink/blob/master/docs/JAVA-HACKING.md) documentation says that to build the Java targets, you should run `bazel test java/...`.

However, there is no `java` directory. The `java_src` directory exists, but trying to build that fails because of path names in subdependencies:
```
% bazel test java_src/...
ERROR: error loading package 'java_src': Unable to load file '//tools:gen_maven_jar_rules.bzl': file doesn't exist
```

This is verified on both 1.5 (ca852750014fb65590585285e2ed7deeb04cb36a) and master (acddae66fbcd38d0502c0e65c051a780eca7d6a1). The bazel version is 3.1.0 on OS X:
```
% bazel version
Build label: 3.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:35:52 2020 (1587551752)
Build timestamp: 1587551752
Build timestamp as int: 1587551752
```

**Comment by chuckx** [comment]
It still needs more clean up, but I addressed the path issue in a quick document update (e891818ab3009f3937571f39ea73df857624b43b).

The relevant background here is that since the document was last updated, the project has been split into multiple Bazel workspaces.  Before invoking Bazel, your working directory needs to be within the desired Bazel workspace.

In this case, the Java workspace is defined in [`java_src/WORKSPACE`](https://github.com/google/tink/blob/master/java_src/WORKSPACE), so you need to navigate to the `java_src` directory first and remove `java/` from the Bazel target pattern.

I'm going to close this issue for now, but will continue cleaning up the documentation. Thanks for pointing this out.

**Comment by sweis** [comment]
The build still fails from the java_src directory, but with different errors.

This is from 71029ffbff34659b75e0a69d2bbf111c99421a00 using bazel 3.1.

```
 java_src % git log -1
commit 71029ffbff34659b75e0a69d2bbf111c99421a00 (HEAD -> master, origin/master, origin/HEAD)
Author: ckl <ckl@google.com>
Date:   Mon Dec 21 16:10:19 2020 -0800

    go/aead: Enforce 32-bit bounds checking for AESGCMSIV input.

    This aligns with the AEAD documentation in:
    https://github.com/google/tink/blob/master/docs/PRIMITIVES.md

    PiperOrigin-RevId: 348544404
```

```
 java_src % bazel version
Build label: 3.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:35:52 2020 (1587551752)
Build timestamp: 1587551752
Build timestamp as int: 1587551752
```

```
java_src % pwd
/Users/steve.weis/repos/tink/java_src
```
```
steve.weis@C02YN218JHD2 java_src % bazel test ...
ERROR: /Users/steve.weis/repos/tink/java_src/BUILD.bazel:172:1: //:tink-android-javadoc depends on @androidsdk//:platforms/android-23/android.jar in repository @androidsdk which failed to fetch. no such package '@androidsdk//': Either the path attribute of android_sdk_repository or the ANDROID_HOME environment variable must be set.
ERROR: Analysis of target '//:tink-android-javadoc' failed; build aborted: no such package '@androidsdk//': Either the path attribute of android_sdk_repository or the ANDROID_HOME environment variable must be set.
INFO: Elapsed time: 0.136s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets c\
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets c\
onfigured)
    currently loading: @bazel_tools//tools/jdk
    Fetching @local_config_cc_toolchains; fetching
    Fetching @rules_java; fetching
```

**Comment by sweis** [comment]
This seems to be working:
`java_src % bzl test tink`

**Comment by sweis** [comment]
I think the issue is that I don't have the Android SDK installed, since I'm not doing any Android development.

I'm going to install it to unblock myself, but the build should probably be able to work if it's not present.

**Comment by sweis** [comment]
@chuckx FYI, I had to install the Android SDK, android-23, and android-26 for 'bazel test ...' to run.

It would be nice to not have to do that if you're not building an Android target.
